name: GitHub Actions Demo
on: 
  push:
    paths-ignore: ./../../.github
  pull_request:
    branches: 
      - main
  schedule:
    - cron: 15 6 * * 0  
jobs:
  build:
    name : Build
    runs-on : ubuntu-latest
    steps:
      - name : log
      run: |
        echo "Branch: ${{github.event}}" 
        echo "Branch: ${{github.ref}}" 
  
  
