name: GitHub Actions Demo
on: 
  push:
    paths-ignore: ./../../.github
  pull_request:
    branches: 
      - main
  schedule:
    - cron: 15 6 * * 0  
jobs:
  build:
    name : Build
    runs-on : ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name : log
        run: |
          echo "Event: ${{github.event_name}}" 
          echo "Branch: ${{github.ref_name}}" 
          echo "Files:"
          git ls-files
          
  
  
