name: Reusable Workflow
on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World
jobs:
  reusable-job:
    name : Hello
    runs-on: ubuntu-latest
    outputs: 
      current-time : ${{ steps.timer.outpus.time }}
    steps:
      - name : Main
        run: |
          echo "Hello"
      - name : Set Time
        id : timer
        run: |
          echo "time=$(date)" >> $GITHUB_OUTPUT

